### ISSUE TITLE
How to get approved?

### ISSUE THREAD

**Issue by ChrisBdk** [youngj/EnvayaSMS#12]
Im sorry for this question, but Im a bit rusty on the PHP..

But how or can I get "approved" when I call the page from a normal browser to read out the messages i stored in a mySQL base?

// Cheers

**Comment by youngj** [comment]
One way is to make a separate PHP script that doesn't have the validation check.

Although, I think it would be helpful for the server libraries to come with code that allows you to test commands from the browser.

**Comment by youngj** [comment]
https://github.com/youngj/EnvayaSMS/blob/master/server/php/example/www/test.html now allows simulating EnvayaSMS's HTTP requests from a normal web browser.
