### ISSUE TITLE
Server address with domain name

### ISSUE THREAD

**Issue by trilogis** [youngj/EnvayaSMS#13]
Add the possibility to have the server address defined with the domain name instead of the ip address
(www.example.com instead of xxx.xxx.xxx.xxx).

Thanks

**Comment by youngj** [comment]
It should already be possible to use either the domain name or the IP address (with either http:// or https:// prefix).

**Comment by trilogis** [comment]
It works on my local network (192.168.1.15) but not on my external server http://www.example.ch/track/log.php.
Same php code.
Any clue why ???

**Comment by youngj** [comment]
(I assume your external server is not literally example.ch.)

Can you open other webpages on your external server from the phone's Browser application?

**Comment by trilogis** [comment]
Yes it works for other pages on the external server from the phone's browser !

This is my real server name:
http://www.trilogis.ch/test/index.php   for a basic browser test
http://www.trilogis.ch/test/log.php     for SMS interface
http://www.trilogis.ch/test/test.html   for SMS test interface

**Comment by youngj** [comment]
Hi,

I figured out that your server trilogis.ch rejects HTTP requests if the User-Agent header is not set. 

The new version of EnvayaSMS now sets the User-Agent header like "EnvayaSMS/<version_name>", e.g. EnvayaSMS/2.0.2. Just upgrade to the latest version on http://sms.envaya.org/install/ and it should work.

Thanks for the bug report!

Jesse

**Comment by trilogis** [comment]
It works now.

Many thanks for your fast and efficient response !
