### ISSUE TITLE
Getting incoming call events, and caller ID

### ISSUE THREAD

**Issue by magixbox** [youngj/EnvayaSMS#21]
Wondering if the incoming call and phone number is available at the Android API? It would be pretty useful for EnavaSMS to report back those events as the phone is usually running unattended.

**Comment by lagrandeours** [comment]
i vote : YES

**Comment by youngj** [comment]
Yes, it is available. I've already implemented incoming call notifications in the Telerivet app (a fork of EnvayaSMS) but still need to merge the change back into EnvayaSMS.

**Comment by magixbox** [comment]
Music to my ears.

**Comment by youngj** [comment]
Implemented in version 2.0.5, on https://play.google.com/store/apps/details?id=org.envaya.sms as well as the Github downloads page.
