### ISSUE TITLE
allow user to forward existing MMS from inbox

### ISSUE THREAD

**Issue by youngj** [youngj/EnvayaSMS#4]
Currently the Fwd Inbox button only works for SMS messages.

**Comment by mfb** [comment]
This would be a very useful improvement :)

**Comment by regaladys** [comment]
If the phone goes offline, the MMS messages Envaya missed can be manually sent later. :) Loads of help.

**Comment by youngj** [comment]
This is implemented in version 3.0.

Version 3.0 also introduces a new server API and PHP library interface. If you upgrade the app but not the PHP server library, it should still work (possibly with warnings), but updating the PHP library is still highly recommended.

PHP library migration instructions: http://sms.envaya.org/serverapi/upgrade30.html 

Summary of changes in version 3.0: http://sms.envaya.org/history/

Updated Server API documentation: http://sms.envaya.org/serverapi/
