### ISSUE TITLE
support push-based notifications of outgoing SMS

### ISSUE THREAD

**Issue by youngj** [youngj/EnvayaSMS#5]
Android Cloud to Device Messaging Framework seems complicated and too integrated with google, but perhaps MQTT or Deacon would work

**Comment by ricardobeat** [comment]
How about a simple socket connection and predefined messages?

Maybe websockets? That would allow push from browsers too (https://github.com/TooTallNate/Java-WebSocket)

**Comment by youngj** [comment]
Implemented in version 3.0 using AMQP (e.g. RabbitMQ). 

See example: https://github.com/youngj/EnvayaSMS/blob/master/server/php/example/send_sms_amqp.php
