### ISSUE TITLE
user-configurable list of phone numbers to exclude

### ISSUE THREAD

**Issue by youngj** [youngj/EnvayaSMS#6]
Would be useful to have something that's the opposite of the test mode phone numbers, where SMS from particular numbers (e.g. notifications from the mobile network) is delivered into the normal Messaging inbox and not forwarded to the server. Currently KalSMS is hardcoded to do this for all senders with less than 7 digits in their number.

**Comment by magixbox** [comment]
Yes, it makes sense to have such feature. And do away with the hardcoded 7 digits handling - we do need those SMS.

**Comment by youngj** [comment]
Thanks for the input! Could you describe the situation where you need to handle SMS from phone numbers with less than 7 digits? Are these regular mobile phones, or shortcodes?

**Comment by magixbox** [comment]
I am not sure about other countries, but in Malaysia, it is quite common to receive SMS in shortcodes (4 to 6 digits), sending from international gateway or Celco itself.
It is also possible to receive none-numeric sender identity occasionally - which is rare these days as Celco has started to filter them off.

These SMS usually contain essential information such as credit balance notification and usage related alerts.

**Comment by youngj** [comment]
Thanks for the information. 

The purpose of the 7 digit minimum is to avoid forwarding marketing solicitations (typically from shortcodes) and notifications from the mobile network (typically from non-numeric senders). In particular, if EnvayaSMS is configured not to store incoming SMS in the inbox, forwarding notifications from the mobile network can make the phone difficult to manage. 

I think 7 digits is a reasonable default for deployments that only want to forward SMS from "real" mobile users, but I could understand why someone might want to forward all SMS. 

Instead of changing the minimum sender length from 7 to 0 for all EnvayaSMS users, I think there should be a new checkbox setting that allows the user to choose.

**Comment by magixbox** [comment]
Agreed.

Unfortunately crafting out such option (having checkbox setting at Envaya Android app) is really beyond my "programming" capabilities. I'll have to leave that for you good people at Envaya for now.

**Comment by youngj** [comment]
Implemented in 22f8c26da1ff506c797e0dec5d4b22fcb71d3a22 (version 2.0.3)
