### ISSUE TITLE
CharSet error..

### ISSUE THREAD

**Issue by ChrisBdk** [youngj/EnvayaSMS#8]
Hi again..

Just had a new error... I cant get pass the security check, when I get a message with danish chars in it.. (ISO 8859-10)
Getting some weird symbols, and access denied...

Cheers..

// Bjørn

**Comment by youngj** [comment]
Just tested with Arabic, and you're right ... EnvayaSMS seems to encode all non-ASCII characters in the message as %1A in the POST request. Working on a fix.

**Comment by youngj** [comment]
Encoding problem should be fixed in 2.0-beta7: https://github.com/youngj/EnvayaSMS/downloads
